spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/settle
    username: settle
    password: settlepw
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgresql

  batch:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
    streams:
      application-id: dashboard_group

  data:
    redis:
      host: localhost
      port: 6379

slack:
  webhook-url: {{YOUR_SLACK_WEBHOOK_URL}}